# Generated by Django 5.2.1 on 2025-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_remove_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
